### ISSUE TITLE
Ressources not copied on first launch

### ISSUE THREAD

**Issue by benda95280** [benda95280/MyEntities#12]
**Describe the bug**
All ressources are not copied on fist launch, only Config.yml

**To Reproduce**
Install plugin, and launch server.

**Expected behavior**
All ressource should be here, but skins are missing.

**Comment by inxomnyaa** [comment]
I'd like to assign myself to this

One issue i stumbled across is that when you delete the preset images, they would return again

**Comment by inxomnyaa** [comment]
@benda95280 May i get write/repo access so i don't have to work on a fork and resolve issues directly?

**Comment by benda95280** [comment]
> I'd like to assign myself to this
> 
> One issue i stumbled across is that when you delete the preset images, they would return again

Do it only if config.yml is not existing :)

**Comment by benda95280** [comment]
> @benda95280 May i get write/repo access so i don't have to work on a fork and resolve issues directly?

@thebigsmileXD Done
