### ISSUE TITLE
Add support for language file

### ISSUE THREAD

**Issue by benda95280** [benda95280/MyEntities#13]
We need to add multiple language file support.

_Why_: 
Everything is HardCoded for the language, and some action have default message, because cannot be set by configuration of the entity.
(Like the action to repair an item)

**Comment by benda95280** [comment]
@thebigsmileXD Do you now how i can load Yml file from ressource ?
Every information i've found is to copy it before open, like:
```
    // Creates the plugin folder
    @mkdir($this->getDataFolder());
    // Creates the config
    $cfg = new Config($this->getDataFolder()) . "config.yml"), Config::YAML));
```

**Comment by inxomnyaa** [comment]
Have a look at getResource(string path)

Side note: `config.yml` shouldn't be loaded like that ;) Use getDefaultConfig()/saveDefaultConfig() instead ;)

**Comment by benda95280** [comment]
I've just pushed support for language file :)

Seems to be ok, just an error on line 206, in "MyEntities"
If language not defined, seems i cannot define it after, it seems i'm too tired to find why :(

`Side note: config.yml shouldn't be loaded like that ;) Use getDefaultConfig()/saveDefaultConfig() instead ;)
`
Will look that tomorrow, thanks.
