### ISSUE TITLE
Head from a player 

### ISSUE THREAD

**Issue by Daniel-Ric** [benda95280/MyEntities#14]
**Mybe offline players are a problem.**

**A command with which you can get a head from a player. for example / head {player name}.**

**///**

**///**

**Comment by benda95280** [comment]
> Mybe offline players are a problem.

Can you tell me more ?

> A command with which you can get a head from a player. for example / head {player name}.

Like that ?
https://github.com/Enes5519/PlayerHead/tree/master/

**Comment by Daniel-Ric** [comment]
Yeah like that from Enes :D

**Comment by inxomnyaa** [comment]
Finished as of https://github.com/benda95280/MyEntities/commit/4f68781906b66f260c4bafa808d79d331943c7d2

**Comment by inxomnyaa** [comment]
Does Enes' plugin allow getting heads of offline players? From what i saw from the code - no
