### ISSUE TITLE
Kick (Internal server error) on '/mye entity [name]' command execute

### ISSUE THREAD

**Issue by ndggaming** [benda95280/MyEntities#20]
Hi, I have a bug with your plugin, when i try to spawn an entity, the plugin make me crash (internal server error). It make me crash when i write /mye entity [name of the entity].
I have tested the plugin with no other plugins, but it does not change anything. 

If it can help, add a screenshot of the console of my server : ![](https://media.discordapp.net/attachments/585514742408413326/635422406495830016/Capture_decran_283_LI.jpg?width=2882&height=961)

Pocketmine version: 3.9.5
Minecraft Bedrock version: v1.12.0

PS : sorry for my bad english, i'm French ...

**Comment by benda95280** [comment]
Hello,

I'm sorry you'r having some trouble with the plugin, but it's still in Dev/Beta
Currently XenialDan is doing an amazing work on rewrting the plugin, it will be better and amazing soon :)

For your problem, could you try to remove the Phar file, and run it from source ?

Thanks,
Benda (French too 👍 )

**Comment by ndggaming** [comment]
Ok thank's a lot, I will test. And no problem for the bugs i know that it's a big work

**Comment by benda95280** [comment]
@thebigsmileXD :
It seems we don't yet handle the fact that is possible for the skins files (Skin & SkinChange - Maybe geometry too) could be removed after the initialisation ?
When creating an entity, we should check if all needed file are not missing ?
Same after the entity has been created, if the SkinChange is removed from NBT, it could produce an error.

Do it need to be checked when created, and when used ?
Seems interesting to generate an error in console, and block any interaction with entity if anything is missing ? (Maybe push error message to player too)

**Comment by ndggaming** [comment]
So I have tested to run the plugin by download the zip folder from github and after, I have compressed it with devtools but the problem was that the folder with ressources will empty. So I have add into it the ressources who I have taken in the github folder. I did not succeed to make work the plugin. It has been appear in the plugins folder but it doesn't work.
So I don't now how to make work the plugin, maybe it's just that I have not make the right handling ...

**Comment by benda95280** [comment]
Compressed ? 😭 

You can copy everything in the folder, like that:
![image](https://user-images.githubusercontent.com/1539408/67164366-02338000-f37a-11e9-812b-a73268d46e11.png)

Please, when proceed like that, remove the Phar file ...

**Comment by ndggaming** [comment]
It doesn't work 😢

**Comment by inxomnyaa** [comment]
> You can copy everything in the folder, like that:

Not to forget that the virions need to be installed when running from source

**Comment by inxomnyaa** [comment]
AAAAhhh now that i see the image 

you have not enabled `gd`

check php.ini for an entry "gd2" and remove the `;` before that line

(Maybe that progress is different on linux, https://forums.pmmp.io/threads/enable-gd-extension-in-linux-php.5803/ https://forums.pmmp.io/threads/gd-on-php.6532/ https://forums.pmmp.io/threads/how-to-install-gd-lib-in-php-binary.4372/)

**Comment by benda95280** [comment]
I always forget it:

My SRC folder is looking like that:
![image](https://user-images.githubusercontent.com/1539408/67222198-1c7a6600-f42d-11e9-9a14-1e35fc7f4977.png)

**Comment by inxomnyaa** [comment]
Will actually reopen - we should add a check if gd is enabled
`extension_loaded('gd');`

**Comment by ndggaming** [comment]
Probably this problem appear cause I use a host for my server. I think they have not add GD extension on their servers.

**Comment by inxomnyaa** [comment]
Check was added
