### ISSUE TITLE
Invalid value "added entity" for argument #1

### ISSUE THREAD

**Issue by ndggaming** [benda95280/MyEntities#21]
Hello, when I write /mye entities "(the name of the entity i added)", the plugin reply with -> Invalid value "(name of the entity)" for argument #1.

It appear when I add an new entity.

PS: I use the penultimate poggit version because the last one don't work on my server

**Comment by inxomnyaa** [comment]
Haha i was about to add that issue yesterday.
Reason: only the resources entities are in the entities array for some reason

i have to see if i fixed it already 🤔

**Comment by benda95280** [comment]
New version out in March, i'm thinking to work on it again.
If problem is still existing, feel free to open an issue :)
