### ISSUE TITLE
Support for 128px skin size.

### ISSUE THREAD

**Issue by Jean-TKG** [benda95280/MyEntities#24]
Would you add support for 128px skin size for custom entitys

**Comment by inxomnyaa** [comment]
https://github.com/benda95280/MyEntities/blob/master/src/Benda95280/MyEntities/MyEntities.php#L212

Any size is supported. Size limit is only a matter of PMMP

**Comment by benda95280** [comment]
Just for information, i've added a new check earlier :
https://github.com/benda95280/MyEntities/commit/c7a2157fa0aa2eba70c574a543fa49b6c5d630ed

Warning over 128px, and drop it when over 256px, i was having trouble with large skin (RakLib error).

**Comment by inxomnyaa** [comment]
in theory any skin size would work with the new skins (not legacy) but pmmp hasnt implemented them yet
