### ISSUE TITLE
LifeDispenser not placing

### ISSUE THREAD

**Issue by SuperAdam47** [benda95280/MyEntities#6]

**Comment by benda95280** [comment]
Hello,

Somes fixe are going to be uploaded with a little new feature :)
I wait your answer too on your PR.

**Comment by benda95280** [comment]
Could you try again ? (With the lastest commit ?)

**Comment by SuperAdam47** [comment]
i tested but not fixed this bug

**Comment by SuperAdam47** [comment]
command block not placing
![image](https://user-images.githubusercontent.com/16169771/64923210-5f1ea200-d7e0-11e9-99ab-8c2c35cc5cbf.png)

**Comment by benda95280** [comment]
Could you provide:
- Version of Pocketmine ?
- Have you any other plugins ?
- Any message in the console ?

I'm sorry, it works well on my side :)

**Comment by SuperAdam47** [comment]
Pocketmine 3.9.4
Yes
No
Not fixed

**Comment by benda95280** [comment]
I'm working on 3.8.6 :

I will upgrade my PMMP to the next version in some days.
(Sorry, need to check every plugin, and update if necessary)

Just wait a little, will be fixed **asap**.

**Comment by SuperAdam47** [comment]
I don't think the error is caused by another plugin.
![Ekran Alıntısı](https://user-images.githubusercontent.com/16169771/64926822-ee40af80-d80a-11e9-9cf9-903cbf343605.PNG)

**Comment by benda95280** [comment]
Thanks, try to fix it next week (if i'm able to reproduce ;) )

**Comment by benda95280** [comment]
I'm on runing on 3.9.4 Server version now.
Life dispenser have a little bug when placed ... but works as expected.

**Comment by benda95280** [comment]
Have you been able to try again ? What is the command you type to get it ?

**Comment by SuperAdam47** [comment]
[Server thread/CRITICAL]: TypeError: "imagedestroy() expects parameter 1 to be resource, bool given" (EXCEPTION) in "plugins/MyEntities-maste/src/Benda95280/MyEntities/MyEntities" at line 203

**Comment by inxomnyaa** [comment]
Sounds more like invalid or inaccessible path to images

**Comment by inxomnyaa** [comment]
Might be an issue with using \\ as directory seperator in https://github.com/benda95280/MyEntities/blob/master/src/Benda95280/MyEntities/MyEntities.php#L189

I suggest replacing it with DIRECTORY_SEPERATOR

**Comment by benda95280** [comment]
@thebigsmileXD Thanks, will do it asap

**Comment by inxomnyaa** [comment]
PocketMine is also cancelling the command block placement before the BlockPlaceEvent is called. I made a fork and switched it over to END_FRAME, which is placeable, making the LifeDispenser spawn

**Comment by benda95280** [comment]
@thebigsmileXD :
Could you tell me why i'm able to spwn it ?
It seems you've rewrite a lot a things, and added a lot too :)

**Comment by inxomnyaa** [comment]
@benda95280 Which version do you run? Perhaps command blocks can be placed in pmmp nowadays, i am on API 3.9.4, not so sure about the last changes

**Comment by benda95280** [comment]
@thebigsmileXD Was on 3.8.6, now on 3.9.4

**Comment by benda95280** [comment]
@SuperAdam47 Can i close the issue ?
