### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SuperAdam47** [benda95280/MyEntities#8]
[Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\event\entity\EntityDamageEvent::getDamager()" (EXCEPTION) in "plugins/MyEntities-master/src/Benda95280/MyEntities/entities/MyCustomEntity" at line 110

**Comment by benda95280** [comment]
Yes, i've found it too, WIP :)

**Comment by benda95280** [comment]
I'm not able reproduce it with last commit.
Could you try ?

**Comment by SuperAdam47** [comment]
okay wait

**Comment by SuperAdam47** [comment]
fixed thanks
