### ISSUE TITLE
wrong 

### ISSUE THREAD

**Issue by thehexmor** [benda95280/MyEntities#9]
the copying from skins head is not correct
![Screenshot (731)](https://user-images.githubusercontent.com/47923870/65029714-80ec6600-d953-11e9-9a6a-69d2a99f125f.png)

**Comment by benda95280** [comment]
Thanks for the screenshot, i'll take a look asap.

**Comment by benda95280** [comment]
My bad ... Sorry
Could you try again, last commit should be Ok.

**Comment by inxomnyaa** [comment]
As i see from the screenshot, for head entities it might be suggested to make the shadow smaller by setting the BOUNDING_BOX_WIDTH/HEIGHT properties to a small number (not 0, might cause issues, 0.01 is fine)

**Comment by benda95280** [comment]
@thehexmor HAve you been able to try it ?
@thebigsmileXD I'm going to take a look on how to do it, thanks a lot.

**Comment by benda95280** [comment]
I close this issue, it seems to be resolved now.
